/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantprojectg6;

/**
 *
 * @author pim
 */
public class BackLog extends javax.swing.JFrame {

    /**
     * Creates new form BackLog
     */
    public BackLog() {
        initComponents();
        setSize(800,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noCustomer = new javax.swing.JLabel();
        popFood = new javax.swing.JLabel();
        DoneButtom2 = new javax.swing.JButton();
        NumCustxt2 = new javax.swing.JTextField();
        NumCusTxt1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noCustomer.setFont(new java.awt.Font("#TS  Malee Normal", 0, 36)); // NOI18N
        noCustomer.setForeground(new java.awt.Color(224, 224, 55));
        noCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantprojectg6/golden_star.png"))); // NOI18N
        noCustomer.setText("Number of Customer");
        getContentPane().add(noCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 380, 70));

        popFood.setFont(new java.awt.Font("#TS  Malee Normal", 0, 36)); // NOI18N
        popFood.setForeground(new java.awt.Color(224, 224, 55));
        popFood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantprojectg6/golden_star.png"))); // NOI18N
        popFood.setText("Popular Food");
        popFood.setToolTipText("");
        getContentPane().add(popFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        DoneButtom2.setBackground(new java.awt.Color(255, 255, 255));
        DoneButtom2.setFont(new java.awt.Font("Adobe Caslon Pro", 1, 18)); // NOI18N
        DoneButtom2.setText("BACK");
        DoneButtom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtom2ActionPerformed(evt);
            }
        });
        getContentPane().add(DoneButtom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 90, 40));

        NumCustxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumCustxt2ActionPerformed(evt);
            }
        });
        getContentPane().add(NumCustxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 300, 50));

        NumCusTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumCusTxt1ActionPerformed(evt);
            }
        });
        getContentPane().add(NumCusTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 300, 50));

        jLabel1.setFont(new java.awt.Font("#TS  Malee Normal", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantprojectg6/backlog_header.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 800, 190));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantprojectg6/14309876301083205889speech-bubble.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 650, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantprojectg6/bg2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoneButtom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtom2ActionPerformed
        dispose();
        Function1 f = new Function1();
        f.setVisible(true);
    }//GEN-LAST:event_DoneButtom2ActionPerformed

    private void NumCustxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumCustxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumCustxt2ActionPerformed

    private void NumCusTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumCusTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumCusTxt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BackLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoneButtom2;
    private javax.swing.JTextField NumCusTxt1;
    private javax.swing.JTextField NumCustxt2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel noCustomer;
    private javax.swing.JLabel popFood;
    // End of variables declaration//GEN-END:variables
}
