/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantprojectg6;

import edu.sit.cs.db.CSDbDelegate;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author pim
 */
public class BackLog extends javax.swing.JFrame {

    /**
     * Creates new form BackLog
     */
    public BackLog() {
        initComponents();
        setSize(800,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popFood = new javax.swing.JLabel();
        noCustomer = new javax.swing.JLabel();
        DoneButtom2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        popFood.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        popFood.setForeground(new java.awt.Color(224, 224, 55));
        popFood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantprojectg6/Picture/golden_star.png"))); // NOI18N
        popFood.setText("Popular Food");
        popFood.setToolTipText("");
        getContentPane().add(popFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 290, 70));

        noCustomer.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        noCustomer.setForeground(new java.awt.Color(224, 224, 55));
        noCustomer.setText("Number of Customer");
        getContentPane().add(noCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 290, 80));

        DoneButtom2.setBackground(new java.awt.Color(255, 255, 255));
        DoneButtom2.setFont(new java.awt.Font("Adobe Caslon Pro", 1, 18)); // NOI18N
        DoneButtom2.setText("BACK");
        DoneButtom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtom2ActionPerformed(evt);
            }
        });
        getContentPane().add(DoneButtom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantprojectg6/Picture/cakey.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 170, 390));

        jLabel4.setFont(new java.awt.Font("#TS  Malee Normal", 0, 55)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Backlog");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 200, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantprojectg6/Picture/head1.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 650, 80));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 230, 40));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 190, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantprojectg6/Picture/bg2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoneButtom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtom2ActionPerformed
        dispose();
        Function1 f = new Function1();
        f.setVisible(true);
    }//GEN-LAST:event_DoneButtom2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BackLog().setVisible(true);
            }
        });
    }
    
    public void setPop(){
        CSDbDelegate db = new CSDbDelegate("csprog-in.sit.kmutt.ac.th", "3306", "CSC105_G6", "csc105_2014", "csc105");
        System.out.println(db.connect());
        String sql = "select foodName from RESTAURANT_Food where count in (select max(count) from RESTAURANT_Food)";

        ArrayList<HashMap> pop = db.queryRows(sql);

        for (HashMap p : pop) {
            jLabel5.setText((String)p.get("foodName"));
        }
        
        db.disconnect();
       
        System.out.println(sql);
    }
    
    public void setCus(){
        CSDbDelegate db = new CSDbDelegate("csprog-in.sit.kmutt.ac.th", "3306", "CSC105_G6", "csc105_2014", "csc105");
        System.out.println(db.connect());
        String sql = "select COUNT(no) from RESTAURANT_CustomerInfo";

        ArrayList<HashMap> pop = db.queryRows(sql);

        for (HashMap p : pop) {
            jLabel6.setText((String)p.get("COUNT(no)"));
        }
        
        db.disconnect();
       
        System.out.println(sql);
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoneButtom2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel noCustomer;
    private javax.swing.JLabel popFood;
    // End of variables declaration//GEN-END:variables
}
